#https://download.opensuse.org/repositories/isv:/ownCloud:/server:/10/Ubuntu_18.04/all/owncloud-complete-files_10.8.0-1+3.1_all.deb


name: Test Cloud

on:
  push:
    branches: [master]

jobs:
       
  archive-build-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Step 0 - Get Informaton run OS
        run: |
            lsb_release -a
            uname -a
      
      - name: Step 1 - Create a temporary artifact downloads folder
        run: mkdir downloads
        
      - name: step 2 - Add artifacts to publish to the temp folder
        run: |
          cd downloads
    
     # - name: Step 3 - Use the Upload Artifact GitHub Action
      #  uses: actions/upload-artifact@v2
       # with: 
        #  name: assets-for-download
         # path: downloads 
          
            
      - name: Step 5 - update settings
        run: |
            sudo service ssh restart
            
            
      - name: Step 6 - test su command
        #uses: build
        #shell: bash
        #working-directory: build
        run: |
              set -x
              #sudo apt install curl -y
              curl https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip -o ngrx.zip
              echo .
              #curl https://download.opensuse.org/repositories/isv:/ownCloud:/server:/10/Ubuntu_20.04/all/owncloud-complete-files_10.8.0-1+3.1_all.deb -o owncloud.deb
              #sudo dpkg -i owncloud.deb
              sudo service start nginx
              wget https://download.owncloud.org/community/owncloud-10.0.8.tar.bz2
              wget https://download.owncloud.org/community/owncloud-10.0.8.tar.bz2.sha256
              sha256sum -c owncloud-10.0.8.tar.bz2.sha256 < owncloud-10.0.8.tar.bz2
              #nginx
              #tar xvjf owncloud-10.0.8.tar.bz2
              echo .
              echo Server Starting ...
              unzip ngrx.zip
              ./ngrok authtoken 1nKiWABerQ8KRNh8bRgG1pAzwLa_4P1qGtfGmTC8uBWa3bVK5
              ./ngrok http 80
