name: Windows HOST

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # The first job in this workflow is named build-on-windows
  build-on-windows:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      - name: Step 1 - Log the pre-build disc space
        run: ls
        
      - name: step 2 - Checkout the main GitHub branch
        uses: actions/checkout@v2 
        
      #- name: Step 3 - Set up JDK 1.8
       # uses: actions/setup-java@v1
        #with: 
         # java-version: 1.8

     # - name: Step 4 - Build your your Jakarta web app with Maven
      #  run: echo mvn -B package --file pom.xml
        
      - name: Step 5 - Check Windows Execution Policy
        run: |
          echo Here is the Windows ExecutionPolicy:
          Get-ExecutionPolicy
          
     # - name: Step 6 - List Windows Environment Variables
      #  run: env
        
      - name: Step 7 - Server Setup
        run: | 
          cmd /c "mkdir test"
          cd "Test"
          Invoke-WebRequest -Uri "https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip" -OutFile "D:\a\ubuntu-1\ubuntu-1\test\ngnx.zip"
          dir
          Expand-Archive -Force 'D:\a\ubuntu-1\ubuntu-1\test\ngnx.zip' '%n'
          #cmd -c "C:"

